In [1]:
import kcf_api_calls
import os
import re
import pandas as pd
import outlook

In [2]:
def remove_condor_list(pumplist):
    for condor in condors:
        pumplist = list(filter(lambda a: a != condor, pumplist))
    return pumplist

condors = ['41', '44', '43', '45', '120', '121', '122', '134', '147',
           '149', '164', '181', '183', '185', '190', '189']

In [3]:
def find_condor(df, column):
    try:
        return int(re.search(r'''
                           >\s
                           (?P<pump>[0-9]+)
                           ?\s>
                            ''', df[column][0], re.X).group(1))
    except (TypeError, AttributeError) as e:
        return 0

In [4]:
def find_extra(df, column):
    try:
        return re.search(r'''
                        (?P<extra>>\s\w{2}\s\w+\s>\s)
                        ''', df[column][0], re.X).group(1)
    except (TypeError, AttributeError) as e:
        return 0

In [5]:
directory = r'C:\Users\austi\Desktop\React Nanodegree\MyReads Project\myreads\Daily_KCF_Report_Current\test'

for file in os.listdir(directory):
    with open(os.path.join(directory, file)) as stuff:
        data = stuff.read()
        pumplist = re.findall(r'''
                       >\s
                       (?P<pump>[0-9]+)
                       ?\s>
                        ''', data, re.X)

        holes = []

In [6]:
print(holes)

[]

In [7]:
csv_file_path = os.path.join(directory, file)

In [8]:
kcf = pd.read_csv(csv_file_path, header=None, dtype=object)
with open(csv_file_path) as stuff:
    data = stuff.read()

    pumplist = remove_condor_list(pumplist)

    kcf.fillna(0, inplace=True)

    kcf = kcf.loc[:, (kcf != 0).any(axis=0)]
    columns = []

    for column in kcf.columns:
        if kcf[column][0] != 0:
            columns.append(column)
        else:
            continue
    to_delete = []

In [9]:
kcf.head()

,0,1,2,3,5,6,7,8,10,11,...,167,168,170,171,172,173,175,176,177,178
0,New Odessa Master > 108 > Fluid End > Hole 5 >...,0,0,0,New Odessa Master > 747 > Fluid End > Hole 5 >...,0,0,0,New Odessa Master > 143 > Fluid End > Hole 1 >...,0,...,0,0,New Odessa Master > 748 > Fluid End > Hole 5 >...,0,0,0,New Odessa Master > 745 > Fluid End > Hole 1 >...,0,0,0
1,Time (UTC),Avg(Damage),Min(Damage),Max(Damage),Time (UTC),Avg(Damage),Min(Damage),Max(Damage),Time (UTC),Avg(Damage),...,Min(Damage),Max(Damage),Time (UTC),Avg(Damage),Min(Damage),Max(Damage),Time (UTC),Avg(Damage),Min(Damage),Max(Damage)
2,9/18/2018 1:00:20 PM,0.3796948,0.3796948,0.3796948,0,0,0,0,9/18/2018 1:00:42 PM,0.6113704,...,0.5222591,0.5222591,9/18/2018 1:00:18 PM,0.4809208,0.4809208,0.4809208,9/18/2018 1:00:27 PM,0.5034005,0.5034005,0.5034005
3,9/18/2018 1:01:21 PM,0.4210468,0.4210468,0.4210468,0,0,0,0,9/18/2018 1:01:42 PM,0.6229494,...,0.4967317,0.4967317,9/18/2018 1:01:19 PM,0.4304021,0.4304021,0.4304021,9/18/2018 1:01:28 PM,0.5004986,0.5004986,0.5004986
4,9/18/2018 1:02:21 PM,0.4118623,0.4118623,0.4118623,0,0,0,0,9/18/2018 1:02:43 PM,0.5909964,...,0.4952379,0.4952379,9/18/2018 1:02:19 PM,0.4351767,0.4351767,0.4351767,9/18/2018 1:02:28 PM,0.5115094,0.5115094,0.5115094

In [10]:
kcf.to_csv(r'C:\Users\austi\Desktop\React Nanodegree\MyReads Project\myreads\Daily_KCF_Report_Current\test\test.csv')

In [11]:
kcf[0][0]

'New Odessa Master > 108 > Fluid End > Hole 5 > Damage Accumulation'

In [12]:
for column in columns:
    for condor in condors:
        if int(condor) == find_condor(kcf, column):
            to_delete.append(column)
            to_delete.append(column + 1)
            to_delete.append(column + 2)
            to_delete.append(column + 3)

In [13]:
to_delete

[105, 106, 107, 108, 115, 116, 117, 118]

In [14]:
find_extra(kcf, column)

0

In [15]:
kcf.drop(labels=to_delete, axis=1, inplace=True)
for column in kcf.columns:
    try:
        holes.append(re.search(r'''
               (?P<hole>>\s\w+\s\d\s>)
                ''', kcf[column][0], re.X).group(1))
    except TypeError:
        pass

for condor in to_delete:
    if condor in columns:
        columns.remove(condor)

In [16]:
holes

['> Hole 5 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 1 >',
 '> Hole 5 >',
 '> Hole 5 >',
 '> Hole 1 >']

In [17]:
Hone = True
for pump, column, hole in zip(pumplist, columns, holes):

    if kcf[column][0] != 0:
        if Hone:
            kcf.loc[(1, column + 1)] = pump + " " + hole
            Hone = False
        else:
            kcf.loc[(1, column + 1)] = pump + " " + hole
            Hone = True
    kcf.drop(labels=[column + 2, column + 3], axis=1, inplace=True)
kcf.drop(labels=0, inplace=True)
kcf.set_index(kcf.astype(bool).sum(axis=0).idxmax(), inplace=True)
kcf.columns = kcf.iloc[0]
cols = [c for c in kcf.columns if c != 'Time (UTC)']

In [18]:
kcf

Time (UTC),Time (UTC),108 > Hole 5 >,Time (UTC),747 > Hole 5 >,Time (UTC),143 > Hole 1 >,Time (UTC),670 > Hole 1 >,330 > Hole 1 >,Time (UTC),...,Time (UTC),113 > Hole 5 >,Time (UTC),108 > Hole 1 >,Time (UTC),472 > Hole 5 >,Time (UTC),748 > Hole 5 >,Time (UTC),745 > Hole 1 >
20,,,,,,,,,,,,,,,,,,,,,
Time (UTC),Time (UTC),108 > Hole 5 >,Time (UTC),747 > Hole 5 >,Time (UTC),143 > Hole 1 >,Time (UTC),670 > Hole 1 >,330 > Hole 1 >,Time (UTC),...,Time (UTC),113 > Hole 5 >,Time (UTC),108 > Hole 1 >,Time (UTC),472 > Hole 5 >,Time (UTC),748 > Hole 5 >,Time (UTC),745 > Hole 1 >
9/18/2018 1:00:17 PM,9/18/2018 1:00:20 PM,0.3796948,0,0,9/18/2018 1:00:42 PM,0.6113704,9/18/2018 1:00:22 PM,0.6476453,0.5608702,9/18/2018 1:00:49 PM,...,9/18/2018 1:00:22 PM,0.4133951,9/18/2018 1:01:00 PM,0.4495834,9/18/2018 1:00:20 PM,0.5222591,9/18/2018 1:00:18 PM,0.4809208,9/18/2018 1:00:27 PM,0.5034005
9/18/2018 1:01:18 PM,9/18/2018 1:01:21 PM,0.4210468,0,0,9/18/2018 1:01:42 PM,0.6229494,9/18/2018 1:01:23 PM,8.8972014,0.5427261,9/18/2018 1:01:49 PM,...,9/18/2018 1:01:22 PM,0.3615215,9/18/2018 1:02:00 PM,0.4922863,9/18/2018 1:01:20 PM,0.4967317,9/18/2018 1:01:19 PM,0.4304021,9/18/2018 1:01:28 PM,0.5004986
9/18/2018 1:02:18 PM,9/18/2018 1:02:21 PM,0.4118623,0,0,9/18/2018 1:02:43 PM,0.5909964,9/18/2018 1:02:23 PM,0.6491678,0.5299214,9/18/2018 1:05:51 PM,...,9/18/2018 1:02:23 PM,0.3645235,9/18/2018 1:04:02 PM,0.4292093,9/18/2018 1:02:21 PM,0.4952379,9/18/2018 1:02:19 PM,0.4351767,9/18/2018 1:02:28 PM,0.5115094
9/18/2018 1:03:19 PM,9/18/2018 1:05:23 PM,0.3922066,0,0,9/18/2018 1:03:43 PM,0.5962426,9/18/2018 1:03:24 PM,0.6324711,0.5141968,0,...,9/18/2018 1:03:23 PM,0.4281578,9/18/2018 1:05:02 PM,0.4808538,9/18/2018 1:03:21 PM,0.4832907,9/18/2018 1:03:20 PM,0.4217501,9/18/2018 1:03:29 PM,0.4928937
9/18/2018 1:04:19 PM,9/18/2018 1:06:24 PM,0.3989038,0,0,9/18/2018 1:04:44 PM,0.5832056,9/18/2018 1:06:25 PM,0.6203096,0.557929,0,...,9/18/2018 1:04:24 PM,0.4837582,9/18/2018 1:06:02 PM,0.4718586,9/18/2018 1:04:22 PM,0.4957775,9/18/2018 1:04:21 PM,0.4111252,9/18/2018 1:04:29 PM,0.4772513
9/18/2018 1:05:20 PM,0,0,0,0,9/18/2018 1:05:44 PM,0.6224597,0,0,0.5406391,0,...,9/18/2018 1:05:24 PM,0.4142666,0,0,9/18/2018 1:05:22 PM,0.5174095,9/18/2018 1:05:21 PM,0.4554328,9/18/2018 1:06:30 PM,0.4544757
9/18/2018 1:06:20 PM,0,0,0,0,0,0,0,0,0.5740682,0,...,9/18/2018 1:06:25 PM,0.4479671,0,0,9/18/2018 1:06:22 PM,0.4731019,9/18/2018 1:06:22 PM,0.4851915,0,0

In [19]:
kcf_filtered = kcf[cols].drop('Time (UTC)')

In [20]:
kcf_filtered

Time (UTC),108 > Hole 5 >,747 > Hole 5 >,143 > Hole 1 >,670 > Hole 1 >,330 > Hole 1 >,480 > Hole 1 >,472 > Hole 1 >,670 > Hole 5 >,113 > Hole 1 >,746 > Hole 1 >,...,493 > Hole 1 >,463 > Hole 1 >,474 > Hole 1 >,747 > Hole 1 >,143 > Hole 5 >,113 > Hole 5 >,108 > Hole 1 >,472 > Hole 5 >,748 > Hole 5 >,745 > Hole 1 >
20,,,,,,,,,,,,,,,,,,,,,
9/18/2018 1:00:17 PM,0.3796948,0,0.6113704,0.6476453,0.5608702,0.5643008,0,0.6365596,0.3813419,0.5548739,...,0.561524,0.5630261,0,0,0.6444216,0.4133951,0.4495834,0.5222591,0.4809208,0.5034005
9/18/2018 1:01:18 PM,0.4210468,0,0.6229494,8.8972014,0.5427261,0.5414716,0,0.6110465,0.5144967,0.6065363,...,0.572088,0.5260804,0,0,0.5887888,0.3615215,0.4922863,0.4967317,0.4304021,0.5004986
9/18/2018 1:02:18 PM,0.4118623,0,0.5909964,0.6491678,0.5299214,0.5142789,0,0.6002072,0.5465069,0.5508998,...,0.5104727,0.5610891,0,0,0.6042096,0.3645235,0.4292093,0.4952379,0.4351767,0.5115094
9/18/2018 1:03:19 PM,0.3922066,0,0.5962426,0.6324711,0.5141968,0,0,0.6336148,0.4673659,0.5340102,...,0.5124169,0.5911302,0,0,0.6439641,0.4281578,0.4808538,0.4832907,0.4217501,0.4928937
9/18/2018 1:04:19 PM,0.3989038,0,0.5832056,0.6203096,0.557929,0,0,0.5982953,0.353538,0.5126498,...,0,0.567479,0,0,0.6497144,0.4837582,0.4718586,0.4957775,0.4111252,0.4772513
9/18/2018 1:05:20 PM,0,0,0.6224597,0,0.5406391,0,0,0.5971767,0.5572604,0.5106629,...,0,0.5250905,0,0,0.6004714,0.4142666,0,0.5174095,0.4554328,0.4544757
9/18/2018 1:06:20 PM,0,0,0,0,0.5740682,0,0,0,0,0,...,0,0.5413798,0,0,0,0.4479671,0,0.4731019,0.4851915,0

In [21]:
kcf_fn = kcf_filtered.apply(pd.to_numeric)
kcf_fn = kcf_fn.loc[:, (kcf_fn != 0).any(axis=0)]

In [54]:
trend = 'fluid'
tag_df = kcf_fn[kcf_fn > 5]
tag_df.fillna(0, inplace=True)
if trend == 'fluid':
    tags = count_tags(tag_df)
else:
    tags = 0
kcf_greater = kcf_fn[kcf_fn > .65]
unique_pump_list = []
for pump in pumplist:
    if pump not in unique_pump_list:
        unique_pump_list.append(pump)
kcf_average = pd.DataFrame(columns=unique_pump_list)
for unique_pump in unique_pump_list:
    i = 0
    for index in kcf_greater.mean(axis=0).index:
        if unique_pump == index[0:len(unique_pump)]:
            if i <= 1:
                kcf_average[unique_pump].loc[i] = kcf_greater.mean(axis=0)[index]
                i += 1
kcf_final = pd.DataFrame()
for pump in kcf_average.columns:
    kcf_final[pump] = kcf_average[pump]
    largest = kcf_final.mean().nlargest(n=3).index.tolist()
    smallest = kcf_final.mean().nsmallest(n=3).index.tolist()
    averageDA = round(kcf_final.mean().mean(), 1)
pump_change = []

In [22]:
kcf_greater = kcf_fn[kcf_fn > .65]
unique_pump_list = []
for pump in pumplist:
    if pump not in unique_pump_list:
        unique_pump_list.append(pump)
kcf_average = pd.DataFrame(columns=unique_pump_list)
for unique_pump in unique_pump_list:
    i = 0
    for index in kcf_greater.mean(axis=0).index:
        if unique_pump == index[0:len(unique_pump)]:
            if i <= 1:
                kcf_average[unique_pump].loc[i] = kcf_greater.mean(axis=0)[index]
                i += 1
kcf_final = pd.DataFrame()
for pump in kcf_average.columns:
    kcf_final[pump] = kcf_average[pump]
    largest = kcf_final.mean().nlargest(n=3).index.tolist()
    smallest = kcf_final.mean().nsmallest(n=3).index.tolist()
    averageDA = round(kcf_final.mean().mean(), 1)

In [56]:
largest

['09', '06', '393']

In [57]:
averageDA

1.8